### ISSUE TITLE
Seed development database with dummy data

### ISSUE THREAD

**Issue by fredlawl** [codeforkansascity/tagging_tracker_backend#36]
Currently the project does not have any dummy data in the database. This makes endpoint testing difficult because there's no data to work with. As a consequence, developers must supply their own data to use the API during development. 

I propose that a database seed script is added to the project such that on launch or build of the docker  container that the database not only has it's tables created, but also that seed data gets created too.

**Comment by kolkheang** [comment]
+1

**Comment by AmandaWilsonKC** [comment]
https://github.com/codeforkansascity/tagging-tracker/issues/11

**Comment by AmandaWilsonKC** [comment]
[TaggingTrackerDummyData.xlsx](https://github.com/codeforkansascity/tagging_tracker_backend/files/2221569/TaggingTrackerDummyData.xlsx)

**Comment by fredlawl** [comment]
Thank you Amanda for the upload, and I see that in the spreadsheet that there appears to be missing row data. Did you mean to leave out that data or were you only intending on listing out the column headers?

**Comment by AmandaWilsonKC** [comment]
Yep, I didn't get the dummy data in there yet. will do that at next hack night. cool?

**Comment by AmandaWilsonKC** [comment]
![dsc03194](https://user-images.githubusercontent.com/22461039/46322978-96854600-c5b1-11e8-8118-01384f9bbb61.jpg)

**Comment by AmandaWilsonKC** [comment]
![dsc03124](https://user-images.githubusercontent.com/22461039/46323279-24adfc00-c5b3-11e8-94e2-fd60c570f5ed.jpg)
![dsc03128](https://user-images.githubusercontent.com/22461039/46323280-24adfc00-c5b3-11e8-93e6-4a5ce79563a0.jpg)
![dsc03139](https://user-images.githubusercontent.com/22461039/46323281-24adfc00-c5b3-11e8-813b-3430bd371821.jpg)

**Comment by Amertz08** [comment]
Coworker pointed [this](https://github.com/joke2k/faker) library out the other day. It can get names, addresses, etc.
