### ISSUE TITLE
Remove fatal error from missing log file when testing

### ISSUE THREAD

**Issue by dwill21** [codeforkansascity/tagging_tracker_backend#48]
In the docker container we use /code/logs/error.log for logging. However, when testing (i.e. running `./manage.py test`), Django still searches for this file. Upon not finding it, it crashes without running any tests.

This should be changed so that the tests can be run without needing /code/logs/error.log to exist.

**Comment by fredlawl** [comment]
Are you able to verify this workaround: `docker-compose up --build`? That should create that `error_log` for you automatically. I suspect that the underlying issue is due to pull request #43

**Comment by fredlawl** [comment]
Created pull request #59

**Comment by Amertz08** [comment]
Resolved #59
