### ISSUE TITLE
Azure re-upping

### ISSUE THREAD

**Issue by Nerdenator** [codeforkansascity/tagging_tracker_backend#60]
Amanda needs to log into azure to see what our money situation is. Investigate possible hosting alternatives

**Comment by AmandaWilsonKC** [comment]
ok, just emailed Microsoft Azure to request renewal.

**Comment by AmandaWilsonKC** [comment]
Done! 

From: Oluchukwu Omanukwue (Tek Experts) <v-oloman@microsoft.com>
Sent: Wednesday, November 28, 2018 4:16 AM
To: Amanda Wilson
Cc: MSSolve Case Email
Subject: RE: [REG:118110621000209] ] Renew Nonprofit Azure Subscription

Hello Amanda,

Please be informed that your AIRS 104692 for awilson@lisckc.onmicrosoft.com has been renewed. New sponsorship end date is 11/27/2019. Your $3,500 balance is reset.

Note that the Azure donation offer has been modified in response to feedback from our nonprofit customers.
The total donation value of Azure services available with this offer is still valued at $5,000 (USD), but will now include Azure Active Directory Premium via a donated Enterprise Mobility + Security E3 subscription valued at $1,500 (USD). Thus, our Azure credit offer will include $3,500 (USD) for any Azure services in your Azure Admin Portal, and 50 licenses of donated Enterprise Mobility + Security E3 available through your O365 Admin Portal.

Kindly approve that I convert the Pay-As-you-go subscription to sponsorship to align the credits.

I look forward to hearing from you.

Thank you.
Best Regards,
Oluchukwu Omanukwue| Support Engineer | Azure Billing and Subscription Team
Email: v-oloman@microsoft.com | Manager: v-maegom@microsoft.com
Working Hours: 6:00 AM- 3:00PM  (Mon-Fri) UTC  | Local Time
