### ISSUE TITLE
Switch Docker base image from python:3.6 to an Alpine image.

### ISSUE THREAD

**Issue by Nerdenator** [codeforkansascity/tagging_tracker_backend#99]
Reading through https://blog.realkinetic.com/building-minimal-docker-containers-for-python-applications-37d0272c52f3 and there may be benefits to switching from python:3.6 to python:3.6-alpine, which is a very lightweight distribution. Could take up less space on developer devices, and reduce possible attack surface in eventual production environments.

**Comment by Amertz08** [comment]
Fine by me. This wouldn't be the first article I read that complains about the python3.6 image size.

**Comment by Nerdenator** [comment]
https://github.com/gliderlabs/docker-alpine/issues/158

**Comment by Nerdenator** [comment]
https://stackoverflow.com/questions/46711990/error-pg-config-executable-not-found-when-installing-psycopg2-on-alpine-in-dock

**Comment by Nerdenator** [comment]
https://github.com/petr-k/gdal-python-alpine/blob/master/Dockerfile
